update(dotupdate): big overhaul

diff --git a/bin/dotupdate b/bin/dotupdate
--- a/bin/dotupdate
+++ b/bin/dotupdate
@@ -1,21 +1,54 @@
 #!/bin/env bash
 
-current_dir=$(pwd)
+function update_from_repository() {
+	# Stash any uncommitted changes
+	git stash save "Temporary stash for pull"
 
-desired_dir="$HOME/dotfiles/"
-cd "$desired_dir" || exit
+	# Pull the latest changes
+	git pull
 
-# Stash any uncommitted changes
-git stash save "Temporary stash for pull"
+	# Pop (reapply) the stashed changes
+	git stash pop
+}
 
-# Pull the latest changes
-git pull
+function run_installation_script() {
+	# Run the installation script
+	bash "$HOME/dotfiles/install.sh"
+}
 
-# Pop (reapply) the stashed changes
-git stash pop
+function reload_shell() {
+	local current_shell
+	current_shell=$(basename "$SHELL")
 
-# Run the installation script
-bash "$HOME/dotfiles/install.sh"
+	if [[ $current_shell == "zsh" ]]; then
+		exec zsh
+		source "$HOME/.zshrc"
+	elif [[ $current_shell == "bash" ]]; then
+		exec bash
+		source "$HOME/.bashrc"
+	else
+		echo "Error: Unknown shell: $current_shell"
+	fi
+}
 
-# Return to the original directory
-cd "$current_dir" || exit
+function main() {
+	local current_dir
+	local desired_dir
+
+	# Get the current directory
+	current_dir=$(pwd)
+
+	# Change to the dotfiles directory
+	desired_dir="$HOME/dotfiles/"
+	cd "$desired_dir" || exit
+
+	# Update the repository
+	update_from_repository
+	run_installation_script
+	reload_shell
+
+	# Return to the original directory
+	cd "$current_dir" || exit
+}
+
+main
