fix(install, dotupdate): now working

diff --git a/bin/dotupdate b/bin/dotupdate
--- a/bin/dotupdate
+++ b/bin/dotupdate
@@ -2,6 +2,63 @@
 
 set -euo pipefail
 
+function update_symlinks() {
+	declare -A symlinks=(
+		# SHELL
+		# # bash
+		[".bashrc"]="$script_dir/bash/bashrc"
+		# # fish
+		[".config/fish"]="$script_dir/fish"
+		# # zsh
+		[".config/zsh"]="$script_dir/zsh"
+		[".zshrc"]="$script_dir/zsh/zshrc"
+		# # shared resources
+		[".aliasrc"]="$script_dir/shell/aliasrc"
+		[".functionsrc"]="$script_dir/shell/functionsrc"
+
+		# GIT
+		[".gitconfig"]="$script_dir/git/gitconfig"
+		[".config/gh"]="$script_dir/gh"
+
+		# CLI
+		# # tmux
+		[".tmux.conf"]="$script_dir/tmux/tmux.conf"
+		# # neofetch
+		[".config/neofetch"]="$script_dir/neofetch"
+		# # starship
+		[".config/starship.toml"]="$script_dir/starship/starship.toml"
+
+		# Desktop applications
+		[".config/dunst"]="$script_dir/dunst"
+		[".config/hypr"]="$script_dir/hypr"
+		[".config/Thunar"]="$script_dir/Thunar"
+		[".config/waybar"]="$script_dir/waybar"
+		[".config/wofi"]="$script_dir/wofi"
+		# # terminal
+		[".config/warp-terminal"]="$script_dir/warp-terminal"
+		[".config/wezterm"]="$script_dir/wezterm"
+	)
+
+	create_symlink() {
+		local source=$1
+		local target=$2
+
+		if [ -e "$target" ]; then
+			echo "Symlink for $source already exists."
+		else
+			ln -s "$source" "$target" || {
+				echo "Failed to create symlink for $source"
+				exit 1
+			}
+			echo "Symlink for $source created."
+		fi
+	}
+
+	for source in "${!symlinks[@]}"; do
+		create_symlink "${symlinks[$source]}" "$HOME/$source"
+	done
+}
+
 function update_dotfiles() {
 	git pull --autostash --rebase || {
 		echo "Failed to update dotfiles"
@@ -40,9 +97,16 @@ function update_user_bin_directory() {
 	done
 }
 
-function run_installation_script() {
-	# Run the installation script
-	bash "$HOME/dotfiles/install.sh"
+function update_wallpapers() {
+	WALLPAPERS_DIR="$HOME/.config/wallpapers"
+	if [ -d "$WALLPAPERS_DIR" ]; then
+		cd "$WALLPAPERS_DIR" || exit
+		git pull || {
+			echo "Failed to update wallpapers"
+			exit 1
+		}
+		cd "$dir_from_cmd_source" || exit
+	fi
 }
 
 function main() {
@@ -60,7 +124,6 @@ function main() {
 	update_dotfiles
 	update_nvim
 	update_user_bin_directory
-	run_installation_script
 
 	# Return to the original directory
 	cd "$dir_from_cmd_source" || exit
